### ISSUE TITLE
Need to fix ByteBuffer

### ISSUE THREAD

**Issue by skyem123** [skyem123/skyeZ80emu#12]
The append functions in (the new) little endian mode do not work.
cf88db97acb0e6c448d23bba6e89813c91ca4772 is the commit that caused this, for reference.

@Victorious3, can you help me with this?

**Comment by Victorious3** [comment]
Uhm... ALT? What is that supposed to be?

**Comment by skyem123** [comment]
ALT is what LITTLE was before I renamed it.
Should I draw a diagram to explain it?

**Comment by skyem123** [comment]
![gr08_iz4](https://cloud.githubusercontent.com/assets/2051085/8042052/542e9c82-0e14-11e5-84bc-a196eaf1e2a5.jpg)

**Comment by skyem123** [comment]
@Victorious3, can you do this?

**Comment by skyem123** [comment]
https://travis-ci.org/skyem123/skyeZ80emu/builds/66353791#L118-L140
The errors, if needed.
Jenkins Errors as well: http://ci.rx14.co.uk/job/Skye/job/skyeZ80emu/1/testReport/

**Comment by skyem123** [comment]
The crashing lines of code are:
https://github.com/skyem123/skyeZ80emu/blob/master/src/main/java/uk/co/skyem/projects/emuZ80/util/buffer/ByteBuffer.java#L108-L109
https://github.com/skyem123/skyeZ80emu/blob/master/src/main/java/uk/co/skyem/projects/emuZ80/util/buffer/ByteBuffer.java#L119-L120
https://github.com/skyem123/skyeZ80emu/blob/master/src/main/java/uk/co/skyem/projects/emuZ80/util/buffer/ByteBuffer.java#L130-L131

**Comment by NikkyAI** [comment]
Closed with 78b610ea1578c156c5b53b839d45f5b64b373cc3
