### ISSUE TITLE
Some sort of 'make' system?

### ISSUE THREAD

**Issue by skyem123** [skyem123/skyeZ80emu#2]
also, a way to create 'projects' that can be opened in IDEs?

**Comment by skyem123** [comment]
I'm assigning @RX14 because he knows gradle stuff (sorry).
He might need to teach me...

**Comment by RX14** [comment]
grr

**Comment by RX14** [comment]
tomorrow skye, tomorrow

**Comment by skyem123** [comment]
Right. It is done!
Now, how do I get it working with my IDE...
